version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "okdesign21"
    labels:
      - "dependencies"
      - "docker"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "okdesign21"
    labels:
      - "dependencies"
      - "github-actions"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "okdesign21"
    labels:
      - "dependencies"
      - "python"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"
